//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;

namespace NovaFramework.Kit.Network.GameLogin.Samples.Runtime
{
/// <summary>
/// NetworkHostKeys
/// </summary>
public partial class TbNetworkHostKeys :
    NovaFramework.Runtime.ITableMap<string, NetworkHostKeys>
{
    private readonly global::System.Collections.Generic.Dictionary<string, NetworkHostKeys> _dataMap;
    private readonly global::System.Collections.Generic.List<NetworkHostKeys> _dataList;

    public TbNetworkHostKeys(JArray _buf)
    {
        _dataMap = new global::System.Collections.Generic.Dictionary<string, NetworkHostKeys>(_buf.Count);
        _dataList = new global::System.Collections.Generic.List<NetworkHostKeys>(_buf.Count);

        foreach(JObject _ele in _buf)
        {
            NetworkHostKeys _v;
            _v = global::NovaFramework.Kit.Network.GameLogin.Samples.Runtime.NetworkHostKeys.DeserializeNetworkHostKeys(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
         }
    }

    public NovaFramework.Runtime.DataTableMode Mode => NovaFramework.Runtime.DataTableMode.Map;

    public global::System.Collections.Generic.IReadOnlyDictionary<string, NetworkHostKeys> DataMap => _dataMap;
    public global::System.Collections.Generic.IReadOnlyList<NetworkHostKeys> DataList => _dataList;

    NetworkHostKeys NovaFramework.Runtime.ITable<NetworkHostKeys>.this[int index] => _dataList[index];

    public NetworkHostKeys GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public NetworkHostKeys Get(string key) => _dataMap[key];
    public NetworkHostKeys this[string key] => _dataMap[key];

    public void ResolveRef(HostKeyTables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}
#pragma warning disable

namespace NovaFramework.Kit.Network.GameLogin.Samples.Runtime
{
public partial class TbNetworkHostKeys
{
    public NetworkHostKeys GameServer => GetOrDefault("GameServer");

    public NetworkHostKeys TGAServer => GetOrDefault("TGAServer");

}
}
#pragma warning restore
