//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;
using NovaFramework.Runtime;

namespace NovaFramework.Sdk.Appsflyer.Samples.Runtime
{

public sealed partial class Demo_VibrateEmphasis : Luban.BeanBase, NovaFramework.Runtime.IVibrateEmphasisRow
{
    public Demo_VibrateEmphasis(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Name = (string)_obj.GetValue("Name");
        Amplitude = (float)_obj.GetValue("Amplitude");
        Frequency = (float)_obj.GetValue("Frequency");
        PreDuration = (float)_obj.GetValue("PreDuration");
        Interval = (float)_obj.GetValue("Interval");
        Order = (int)_obj.GetValue("Order");
    }

    public static Demo_VibrateEmphasis DeserializeDemo_VibrateEmphasis(JToken _buf)
    {
        return new Demo_VibrateEmphasis(_buf);
    }

    /// <summary>
    /// Demo 振动强调组合表
    /// </summary>
    public string Name { get; }
    /// <summary>
    /// 振幅
    /// </summary>
    public float Amplitude { get; }
    /// <summary>
    /// 频率
    /// </summary>
    public float Frequency { get; }
    /// <summary>
    /// 前置等待时长
    /// </summary>
    public float PreDuration { get; }
    /// <summary>
    /// 振动间隔时长
    /// </summary>
    public float Interval { get; }
    /// <summary>
    /// 播放顺序
    /// </summary>
    public int Order { get; }

    public const int __ID__ = -2135283281;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(VibrateEmphasisTables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "Amplitude:" + Amplitude + ","
        + "Frequency:" + Frequency + ","
        + "PreDuration:" + PreDuration + ","
        + "Interval:" + Interval + ","
        + "Order:" + Order + ","
        + "}";
    }
}
}

