// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pb_net_login.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NovaFramework.Kit.Network.GameLogin.Runtime {

  /// <summary>Holder for reflection information generated from pb_net_login.proto</summary>
  public static partial class PbNetLoginReflection {

    #region Descriptor
    /// <summary>File descriptor for pb_net_login.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PbNetLoginReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJwYl9uZXRfbG9naW4ucHJvdG8SK05vdmFGcmFtZXdvcmsuS2l0Lk5ldHdv",
            "cmsuR2FtZUxvZ2luLlJ1bnRpbWUaE3BiX25ldF9oZWFkZXIucHJvdG8icAoN",
            "UGJOZXRMb2dpblJlcRIzCgRoZWFkGAEgASgLMiUuTm92YUZyYW1ld29yay5S",
            "dW50aW1lLlBiTmV0UmVxSGVhZGVyEg8KB29wZW5faWQYAiABKAkSGQoRZm9y",
            "Y2VfbmV3X2FjY291bnQYAyABKAgi+AEKDlBiTmV0TG9naW5SZXNwEjQKBGhl",
            "YWQYASABKAsyJi5Ob3ZhRnJhbWV3b3JrLlJ1bnRpbWUuUGJOZXRSZXNwSGVh",
            "ZGVyEgsKA3VpZBgCIAEoCRIVCg1yZWdpc3Rlcl90aW1lGAMgASgFEhIKCmxv",
            "Z2luX3RpbWUYBCABKAUSDwoHY291bnRyeRgFIAEoCRJPCgZzdGF0dXMYBiAB",
            "KA4yPy5Ob3ZhRnJhbWV3b3JrLktpdC5OZXR3b3JrLkdhbWVMb2dpbi5SdW50",
            "aW1lLlBiTmV0QWNjb3VudFN0YXR1cxIWCg5pc19uZXdfYWNjb3VudBgHIAEo",
            "CCq1AQoSUGJOZXRBY2NvdW50U3RhdHVzEiIKHlBiTmV0QWNjb3VudFN0YXR1",
            "c19VTlNQRUNJRklFRBAAEh0KGVBiTmV0QWNjb3VudFN0YXR1c19OT1JNQUwQ",
            "ARIdChlQYk5ldEFjY291bnRTdGF0dXNfTE9DS0VEEAISHQoZUGJOZXRBY2Nv",
            "dW50U3RhdHVzX0JBTk5FRBADEh4KGlBiTmV0QWNjb3VudFN0YXR1c19ERUxF",
            "VEVEEARiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::NovaFramework.Runtime.PbNetHeaderReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetAccountStatus), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetLoginReq), global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetLoginReq.Parser, new[]{ "Head", "OpenId", "ForceNewAccount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetLoginResp), global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetLoginResp.Parser, new[]{ "Head", "Uid", "RegisterTime", "LoginTime", "Country", "Status", "IsNewAccount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 账号状态枚举：服务端返回的当前账号可用状态
  /// </summary>
  public enum PbNetAccountStatus {
    /// <summary>
    /// 未指定（默认值，禁止实际使用）
    /// </summary>
    [pbr::OriginalName("PbNetAccountStatus_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// 正常，可继续后续业务
    /// </summary>
    [pbr::OriginalName("PbNetAccountStatus_NORMAL")] Normal = 1,
    /// <summary>
    /// 已锁定，通常需申诉解锁
    /// </summary>
    [pbr::OriginalName("PbNetAccountStatus_LOCKED")] Locked = 2,
    /// <summary>
    /// 已封禁，禁止登录
    /// </summary>
    [pbr::OriginalName("PbNetAccountStatus_BANNED")] Banned = 3,
    /// <summary>
    /// 已删除
    /// </summary>
    [pbr::OriginalName("PbNetAccountStatus_DELETED")] Deleted = 4,
  }

  #endregion

  #region Messages
  /// <summary>
  /// 登录请求
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PbNetLoginReq : pb::IMessage<PbNetLoginReq>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PbNetLoginReq> _parser = new pb::MessageParser<PbNetLoginReq>(() => new PbNetLoginReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PbNetLoginReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetLoginReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbNetLoginReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbNetLoginReq(PbNetLoginReq other) : this() {
      head_ = other.head_ != null ? other.head_.Clone() : null;
      openId_ = other.openId_;
      forceNewAccount_ = other.forceNewAccount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbNetLoginReq Clone() {
      return new PbNetLoginReq(this);
    }

    /// <summary>Field number for the "head" field.</summary>
    public const int HeadFieldNumber = 1;
    private global::NovaFramework.Runtime.PbNetReqHeader head_;
    /// <summary>
    /// 请求公共头
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NovaFramework.Runtime.PbNetReqHeader Head {
      get { return head_; }
      set {
        head_ = value;
      }
    }

    /// <summary>Field number for the "open_id" field.</summary>
    public const int OpenIdFieldNumber = 2;
    private string openId_ = "";
    /// <summary>
    /// 渠道侧返回的用户唯一标识（或 token）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OpenId {
      get { return openId_; }
      set {
        openId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "force_new_account" field.</summary>
    public const int ForceNewAccountFieldNumber = 3;
    private bool forceNewAccount_;
    /// <summary>
    /// 是否强制创建新账号（用于绑定/切换账号场景）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool ForceNewAccount {
      get { return forceNewAccount_; }
      set {
        forceNewAccount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PbNetLoginReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PbNetLoginReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Head, other.Head)) return false;
      if (OpenId != other.OpenId) return false;
      if (ForceNewAccount != other.ForceNewAccount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (head_ != null) hash ^= Head.GetHashCode();
      if (OpenId.Length != 0) hash ^= OpenId.GetHashCode();
      if (ForceNewAccount != false) hash ^= ForceNewAccount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (head_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Head);
      }
      if (OpenId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OpenId);
      }
      if (ForceNewAccount != false) {
        output.WriteRawTag(24);
        output.WriteBool(ForceNewAccount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (head_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Head);
      }
      if (OpenId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OpenId);
      }
      if (ForceNewAccount != false) {
        output.WriteRawTag(24);
        output.WriteBool(ForceNewAccount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (head_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Head);
      }
      if (OpenId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OpenId);
      }
      if (ForceNewAccount != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PbNetLoginReq other) {
      if (other == null) {
        return;
      }
      if (other.head_ != null) {
        if (head_ == null) {
          Head = new global::NovaFramework.Runtime.PbNetReqHeader();
        }
        Head.MergeFrom(other.Head);
      }
      if (other.OpenId.Length != 0) {
        OpenId = other.OpenId;
      }
      if (other.ForceNewAccount != false) {
        ForceNewAccount = other.ForceNewAccount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (head_ == null) {
              Head = new global::NovaFramework.Runtime.PbNetReqHeader();
            }
            input.ReadMessage(Head);
            break;
          }
          case 18: {
            OpenId = input.ReadString();
            break;
          }
          case 24: {
            ForceNewAccount = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (head_ == null) {
              Head = new global::NovaFramework.Runtime.PbNetReqHeader();
            }
            input.ReadMessage(Head);
            break;
          }
          case 18: {
            OpenId = input.ReadString();
            break;
          }
          case 24: {
            ForceNewAccount = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// 登录响应
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PbNetLoginResp : pb::IMessage<PbNetLoginResp>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PbNetLoginResp> _parser = new pb::MessageParser<PbNetLoginResp>(() => new PbNetLoginResp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PbNetLoginResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetLoginReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbNetLoginResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbNetLoginResp(PbNetLoginResp other) : this() {
      head_ = other.head_ != null ? other.head_.Clone() : null;
      uid_ = other.uid_;
      registerTime_ = other.registerTime_;
      loginTime_ = other.loginTime_;
      country_ = other.country_;
      status_ = other.status_;
      isNewAccount_ = other.isNewAccount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PbNetLoginResp Clone() {
      return new PbNetLoginResp(this);
    }

    /// <summary>Field number for the "head" field.</summary>
    public const int HeadFieldNumber = 1;
    private global::NovaFramework.Runtime.PbNetRespHeader head_;
    /// <summary>
    /// 响应公共头
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NovaFramework.Runtime.PbNetRespHeader Head {
      get { return head_; }
      set {
        head_ = value;
      }
    }

    /// <summary>Field number for the "uid" field.</summary>
    public const int UidFieldNumber = 2;
    private string uid_ = "";
    /// <summary>
    /// 服务端分配的用户唯一 ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Uid {
      get { return uid_; }
      set {
        uid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "register_time" field.</summary>
    public const int RegisterTimeFieldNumber = 3;
    private int registerTime_;
    /// <summary>
    /// 账号注册时间（秒级 Unix 时间戳）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int RegisterTime {
      get { return registerTime_; }
      set {
        registerTime_ = value;
      }
    }

    /// <summary>Field number for the "login_time" field.</summary>
    public const int LoginTimeFieldNumber = 4;
    private int loginTime_;
    /// <summary>
    /// 本次登录时间（秒级 Unix 时间戳）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LoginTime {
      get { return loginTime_; }
      set {
        loginTime_ = value;
      }
    }

    /// <summary>Field number for the "country" field.</summary>
    public const int CountryFieldNumber = 5;
    private string country_ = "";
    /// <summary>
    /// 根据 IP 解析出的国家/地区代码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Country {
      get { return country_; }
      set {
        country_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 6;
    private global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetAccountStatus status_ = global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetAccountStatus.Unspecified;
    /// <summary>
    /// 当前账号状态
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetAccountStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "is_new_account" field.</summary>
    public const int IsNewAccountFieldNumber = 7;
    private bool isNewAccount_;
    /// <summary>
    /// 是否为本次新注册账号（true 时走新手流程）
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsNewAccount {
      get { return isNewAccount_; }
      set {
        isNewAccount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PbNetLoginResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PbNetLoginResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Head, other.Head)) return false;
      if (Uid != other.Uid) return false;
      if (RegisterTime != other.RegisterTime) return false;
      if (LoginTime != other.LoginTime) return false;
      if (Country != other.Country) return false;
      if (Status != other.Status) return false;
      if (IsNewAccount != other.IsNewAccount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (head_ != null) hash ^= Head.GetHashCode();
      if (Uid.Length != 0) hash ^= Uid.GetHashCode();
      if (RegisterTime != 0) hash ^= RegisterTime.GetHashCode();
      if (LoginTime != 0) hash ^= LoginTime.GetHashCode();
      if (Country.Length != 0) hash ^= Country.GetHashCode();
      if (Status != global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetAccountStatus.Unspecified) hash ^= Status.GetHashCode();
      if (IsNewAccount != false) hash ^= IsNewAccount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (head_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Head);
      }
      if (Uid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Uid);
      }
      if (RegisterTime != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(RegisterTime);
      }
      if (LoginTime != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(LoginTime);
      }
      if (Country.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Country);
      }
      if (Status != global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetAccountStatus.Unspecified) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Status);
      }
      if (IsNewAccount != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsNewAccount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (head_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Head);
      }
      if (Uid.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Uid);
      }
      if (RegisterTime != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(RegisterTime);
      }
      if (LoginTime != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(LoginTime);
      }
      if (Country.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Country);
      }
      if (Status != global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetAccountStatus.Unspecified) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Status);
      }
      if (IsNewAccount != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsNewAccount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (head_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Head);
      }
      if (Uid.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Uid);
      }
      if (RegisterTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(RegisterTime);
      }
      if (LoginTime != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(LoginTime);
      }
      if (Country.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Country);
      }
      if (Status != global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetAccountStatus.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (IsNewAccount != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PbNetLoginResp other) {
      if (other == null) {
        return;
      }
      if (other.head_ != null) {
        if (head_ == null) {
          Head = new global::NovaFramework.Runtime.PbNetRespHeader();
        }
        Head.MergeFrom(other.Head);
      }
      if (other.Uid.Length != 0) {
        Uid = other.Uid;
      }
      if (other.RegisterTime != 0) {
        RegisterTime = other.RegisterTime;
      }
      if (other.LoginTime != 0) {
        LoginTime = other.LoginTime;
      }
      if (other.Country.Length != 0) {
        Country = other.Country;
      }
      if (other.Status != global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetAccountStatus.Unspecified) {
        Status = other.Status;
      }
      if (other.IsNewAccount != false) {
        IsNewAccount = other.IsNewAccount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (head_ == null) {
              Head = new global::NovaFramework.Runtime.PbNetRespHeader();
            }
            input.ReadMessage(Head);
            break;
          }
          case 18: {
            Uid = input.ReadString();
            break;
          }
          case 24: {
            RegisterTime = input.ReadInt32();
            break;
          }
          case 32: {
            LoginTime = input.ReadInt32();
            break;
          }
          case 42: {
            Country = input.ReadString();
            break;
          }
          case 48: {
            Status = (global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetAccountStatus) input.ReadEnum();
            break;
          }
          case 56: {
            IsNewAccount = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (head_ == null) {
              Head = new global::NovaFramework.Runtime.PbNetRespHeader();
            }
            input.ReadMessage(Head);
            break;
          }
          case 18: {
            Uid = input.ReadString();
            break;
          }
          case 24: {
            RegisterTime = input.ReadInt32();
            break;
          }
          case 32: {
            LoginTime = input.ReadInt32();
            break;
          }
          case 42: {
            Country = input.ReadString();
            break;
          }
          case 48: {
            Status = (global::NovaFramework.Kit.Network.GameLogin.Runtime.PbNetAccountStatus) input.ReadEnum();
            break;
          }
          case 56: {
            IsNewAccount = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
