// <nova-generated profile="localization-font" source="Assets/Samples/AIHelpDemo/Excels/Localizations/Fonts" artifact="TbLocalizationFonts.cs" content-hash="sha256:854ef76402664b5421a3671a40edd7c54f05edbc156dcf564fabab8c63e863b7" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace NovaFramework.Sdk.Aihelp.Samples.Runtime
{

/// <summary>
/// LocalizationFonts
/// </summary>
public partial class TbLocalizationFonts :
    NovaFramework.Runtime.ITable<LocalizationFonts>
{
    private readonly global::System.Collections.Generic.List<LocalizationFonts> _dataList;



    public TbLocalizationFonts(JArray _buf)
    {
        _dataList = new global::System.Collections.Generic.List<LocalizationFonts>(_buf.Count);

        foreach(JObject _ele in _buf)
        {
            LocalizationFonts _v;
            _v = global::NovaFramework.Sdk.Aihelp.Samples.Runtime.LocalizationFonts.DeserializeLocalizationFonts(_ele);
            _dataList.Add(_v);
        }
    }

    public NovaFramework.Runtime.DataTableMode Mode => NovaFramework.Runtime.DataTableMode.List;

    public global::System.Collections.Generic.IReadOnlyList<LocalizationFonts> DataList => _dataList;

    public LocalizationFonts this[int index] => _dataList[index];


    public void ResolveRef(LocalizationFontTables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}
}

