// <nova-generated profile="localization-supported-languages" source="Assets/Samples/AIHelpDemo/Excels/Localizations/Texts" artifact="LocalizationSupportedLanguagesTables.cs" content-hash="sha256:a4423dc9f8ec3660da78609cc51b845c3d4242a0e8f81a7078b1b9acd769936a" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace NovaFramework.Sdk.Aihelp.Samples.Runtime
{
public partial class LocalizationSupportedLanguagesTables : NovaFramework.Runtime.ILubanTables
{
    /// <summary>
    /// Localization supported languages
    /// </summary>
    public TbLocalizationSupportedLanguages TbLocalizationSupportedLanguages {get; }

    public LocalizationSupportedLanguagesTables(global::System.Func<string, JArray> loader)
    {
        TbLocalizationSupportedLanguages = new TbLocalizationSupportedLanguages(loader("tblocalizationsupportedlanguages"));
    }

    public void ResolveRef()
    {
        TbLocalizationSupportedLanguages.ResolveRef(this);
    }

    public global::System.Collections.Generic.IReadOnlyList<NovaFramework.Runtime.ITable> GetAllTables()
    {
        return new NovaFramework.Runtime.ITable[]
        {
            TbLocalizationSupportedLanguages,
        };
    }

    /// <summary>
    /// 获取指定类型的 Luban 表实例。
    /// </summary>
    /// <typeparam name="T">Luban 表类型。</typeparam>
    /// <returns>表实例，不存在时返回 null。</returns>
    public T GetTable<T>() where T : class, NovaFramework.Runtime.ITable
    {
        return GetTable(typeof(T)) as T;
    }

    /// <summary>
    /// 根据类型获取 Luban 表实例。
    /// </summary>
    /// <param name="type">表类型。</param>
    /// <returns>表实例，不存在时返回 null。</returns>
    public NovaFramework.Runtime.ITable GetTable(global::System.Type type)
    {
        global::System.Collections.Generic.IReadOnlyList<NovaFramework.Runtime.ITable> allTables = GetAllTables();
        for (int i = 0; i < allTables.Count; i++)
        {
            if (allTables[i].GetType() == type)
            {
                return allTables[i];
            }
        }
        return null;
    }
}

}

