//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;

namespace NovaFramework.Kit.Network.GameLogin.Samples.Runtime
{
/// <summary>
/// ListB
/// </summary>
public partial class TbListB :
    NovaFramework.Runtime.ITable<ListB>
{
    private readonly global::System.Collections.Generic.List<ListB> _dataList;

    public TbListB(JArray _buf)
    {
        _dataList = new global::System.Collections.Generic.List<ListB>(_buf.Count);

        foreach(JObject _ele in _buf)
        {
            ListB _v;
            _v = global::NovaFramework.Kit.Network.GameLogin.Samples.Runtime.ListB.DeserializeListB(_ele);
            _dataList.Add(_v);
        }
    }

    public NovaFramework.Runtime.DataTableMode Mode => NovaFramework.Runtime.DataTableMode.List;

    public global::System.Collections.Generic.IReadOnlyList<ListB> DataList => _dataList;

    public ListB this[int index] => _dataList[index];

    public void ResolveRef(TableTables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}
}

