// <nova-generated profile="localization-supported-languages" source="Assets/Samples/FirebaseDemo/Excels/Localizations/Texts" artifact="LocalizationSupportedLanguage.cs" content-hash="sha256:4c8891d31bb970b038bdcb2d50c6b2f8ea5d9ccf6e294f4c33a793b4a34be5fc" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace NovaFramework.Sdk.Firebase.Samples.Runtime
{

public sealed partial class LocalizationSupportedLanguage : Luban.BeanBase, NovaFramework.Runtime.ILocalizationSupportedLanguageRow
{
    public LocalizationSupportedLanguage(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Name = (string)_obj.GetValue("Name");
    }

    public static LocalizationSupportedLanguage DeserializeLocalizationSupportedLanguage(JToken _buf)
    {
        return new LocalizationSupportedLanguage(_buf);
    }

    /// <summary>
    /// Localization supported languages
    /// </summary>
    public string Name { get; }


    public const int __ID__ = -95351699;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(LocalizationSupportedLanguagesTables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "}";
    }
}
}

