//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;

namespace NovaFramework.Sdk.Firebase.Samples.Runtime
{
/// <summary>
/// Demo_Localization
/// </summary>
public partial class TbDemo_Localization :
    NovaFramework.Runtime.ITableMap<string, Demo_Localization>
{
    private readonly global::System.Collections.Generic.Dictionary<string, Demo_Localization> _dataMap;
    private readonly global::System.Collections.Generic.List<Demo_Localization> _dataList;

    public TbDemo_Localization(JArray _buf)
    {
        _dataMap = new global::System.Collections.Generic.Dictionary<string, Demo_Localization>(_buf.Count);
        _dataList = new global::System.Collections.Generic.List<Demo_Localization>(_buf.Count);

        foreach(JObject _ele in _buf)
        {
            Demo_Localization _v;
            _v = global::NovaFramework.Sdk.Firebase.Samples.Runtime.Demo_Localization.DeserializeDemo_Localization(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
         }
    }

    public NovaFramework.Runtime.DataTableMode Mode => NovaFramework.Runtime.DataTableMode.Map;

    public global::System.Collections.Generic.IReadOnlyDictionary<string, Demo_Localization> DataMap => _dataMap;
    public global::System.Collections.Generic.IReadOnlyList<Demo_Localization> DataList => _dataList;

    Demo_Localization NovaFramework.Runtime.ITable<Demo_Localization>.this[int index] => _dataList[index];

    public Demo_Localization GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Demo_Localization Get(string key) => _dataMap[key];
    public Demo_Localization this[string key] => _dataMap[key];

    public void ResolveRef(LocalizationTextTables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}
#pragma warning disable

namespace NovaFramework.Sdk.Firebase.Samples.Runtime
{
public partial class TbDemo_Localization
{
    public Demo_Localization Demo_Greet => GetOrDefault("Demo_Greet");

    public Demo_Localization Demo_Confirm => GetOrDefault("Demo_Confirm");

    public Demo_Localization Demo_Cancel => GetOrDefault("Demo_Cancel");

    public Demo_Localization Demo_Toast_Tip => GetOrDefault("Demo_Toast_Tip");

    public Demo_Localization Demo_Switch_Lang => GetOrDefault("Demo_Switch_Lang");

}
}
#pragma warning restore
