// <nova-generated profile="localization-font" source="Assets/Samples/DataMasterDemo/Excels/Localizations/Fonts" artifact="LocalizationFonts.cs" content-hash="sha256:454e038b3cb32f62c8666f2d615358f08dbe88fcbaf636bef84b98315b4831bf" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;
using NovaFramework.Runtime;



namespace NovaFramework.Sdk.Datamaster.Samples.Runtime
{

public sealed partial class LocalizationFonts : Luban.BeanBase, NovaFramework.Runtime.ILocalizationFontRow
{
    public LocalizationFonts(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Language = (string)_obj.GetValue("Language");
        Mark = (string)_obj.GetValue("Mark");
        AssetLocation = (string)_obj.GetValue("AssetLocation");
        MaterialName = (string)_obj.GetValue("MaterialName");
        FontSizeScaleRatio = (float)_obj.GetValue("FontSizeScaleRatio");
    }

    public static LocalizationFonts DeserializeLocalizationFonts(JToken _buf)
    {
        return new LocalizationFonts(_buf);
    }

    /// <summary>
    /// 本地化字体
    /// </summary>
    public string Language { get; }
    public string Mark { get; }
    public string AssetLocation { get; }
    public string MaterialName { get; }
    public float FontSizeScaleRatio { get; }


    public const int __ID__ = -612745525;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(LocalizationFontTables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Language:" + Language + ","
        + "Mark:" + Mark + ","
        + "AssetLocation:" + AssetLocation + ","
        + "MaterialName:" + MaterialName + ","
        + "FontSizeScaleRatio:" + FontSizeScaleRatio + ","
        + "}";
    }
}
}

