// <nova-generated profile="sound" source="Assets/Samples/DataMasterDemo/Excels/Sounds" artifact="SoundTables.cs" content-hash="sha256:ff7881b2fda2c39a8e6fe7e6b800c2a2187a4a00851a1044e4595c61f4ae30a3" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace NovaFramework.Sdk.Datamaster.Samples.Runtime
{
public partial class SoundTables : NovaFramework.Runtime.ILubanTables
{
    /// <summary>
    /// Demo_Sound
    /// </summary>
    public TbDemo_Sound TbDemoSound {get; }

    public SoundTables(global::System.Func<string, JArray> loader)
    {
        TbDemoSound = new TbDemo_Sound(loader("tbdemo_sound"));
    }

    public void ResolveRef()
    {
        TbDemoSound.ResolveRef(this);
    }

    public global::System.Collections.Generic.IReadOnlyList<NovaFramework.Runtime.ITable> GetAllTables()
    {
        return new NovaFramework.Runtime.ITable[]
        {
            TbDemoSound,
        };
    }

    /// <summary>
    /// 获取指定类型的 Luban 表实例。
    /// </summary>
    /// <typeparam name="T">Luban 表类型。</typeparam>
    /// <returns>表实例，不存在时返回 null。</returns>
    public T GetTable<T>() where T : class, NovaFramework.Runtime.ITable
    {
        return GetTable(typeof(T)) as T;
    }

    /// <summary>
    /// 根据类型获取 Luban 表实例。
    /// </summary>
    /// <param name="type">表类型。</param>
    /// <returns>表实例，不存在时返回 null。</returns>
    public NovaFramework.Runtime.ITable GetTable(global::System.Type type)
    {
        global::System.Collections.Generic.IReadOnlyList<NovaFramework.Runtime.ITable> allTables = GetAllTables();
        for (int i = 0; i < allTables.Count; i++)
        {
            if (allTables[i].GetType() == type)
            {
                return allTables[i];
            }
        }
        return null;
    }
}

}

