// <nova-generated profile="vibrate-emphasis" source="Assets/Samples/MainDemo/Excels/Vibrates/Emphasis" artifact="TbDemo_VibrateEmphasis.cs" content-hash="sha256:5c8607cf2995d216b7df08ab66aa980414649907fcc23e7684bcf35d28b0d90a" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace NovaFramework.Samples.Runtime
{

/// <summary>
/// Demo_VibrateEmphasis
/// </summary>
public partial class TbDemo_VibrateEmphasis :
    NovaFramework.Runtime.ITable<Demo_VibrateEmphasis>
{
    private readonly global::System.Collections.Generic.List<Demo_VibrateEmphasis> _dataList;



    public TbDemo_VibrateEmphasis(JArray _buf)
    {
        _dataList = new global::System.Collections.Generic.List<Demo_VibrateEmphasis>(_buf.Count);

        foreach(JObject _ele in _buf)
        {
            Demo_VibrateEmphasis _v;
            _v = global::NovaFramework.Samples.Runtime.Demo_VibrateEmphasis.DeserializeDemo_VibrateEmphasis(_ele);
            _dataList.Add(_v);
        }
    }

    public NovaFramework.Runtime.DataTableMode Mode => NovaFramework.Runtime.DataTableMode.List;

    public global::System.Collections.Generic.IReadOnlyList<Demo_VibrateEmphasis> DataList => _dataList;

    public Demo_VibrateEmphasis this[int index] => _dataList[index];


    public void ResolveRef(VibrateEmphasisTables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}
}

