// <nova-generated profile="localization-text" source="Assets/Samples/IAPDemo/Excels/Localizations/Texts" artifact="Demo_Localization.cs" content-hash="sha256:0e589dd2c6918598ad82ed0c6c7b7e04975a9ffe9a9a6c68622ac11fe91def2f" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;
using NovaFramework.Runtime;



namespace NovaFramework.Sdk.IAP.Samples.Runtime
{

public sealed partial class Demo_Localization : Luban.BeanBase, NovaFramework.Runtime.ILocalizationTextRow
{
    public Demo_Localization(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Name = (string)_obj.GetValue("Name");
        Value = (string)_obj.GetValue("Value");
    }

    public static Demo_Localization DeserializeDemo_Localization(JToken _buf)
    {
        return new Demo_Localization(_buf);
    }

    /// <summary>
    /// Demo_Localization
    /// </summary>
    public string Name { get; }
    public string Value { get; }


    public const int __ID__ = -112808075;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(LocalizationTextTables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

