//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;

namespace NovaFramework.Sdk.IAP.Samples.Runtime
{

public sealed partial class Map1 : Luban.BeanBase
{
    public Map1(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Name = (string)_obj.GetValue("Name");
        Desc = (string)_obj.GetValue("Desc");
        Value = (string)_obj.GetValue("Value");
    }

    public static Map1 DeserializeMap1(JToken _buf)
    {
        return new Map1(_buf);
    }

    /// <summary>
    /// Map测试表
    /// </summary>
    public string Name { get; }
    public string Desc { get; }
    public string Value { get; }

    public const int __ID__ = 2390645;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TableTables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

