//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;

namespace NovaFramework.Sdk.IAP.Samples.Runtime
{
/// <summary>
/// Demo_Item
/// </summary>
public partial class TbDemo_Item :
    NovaFramework.Runtime.ITable<Demo_Item>
{
    private readonly global::System.Collections.Generic.List<Demo_Item> _dataList;

    public TbDemo_Item(JArray _buf)
    {
        _dataList = new global::System.Collections.Generic.List<Demo_Item>(_buf.Count);

        foreach(JObject _ele in _buf)
        {
            Demo_Item _v;
            _v = global::NovaFramework.Sdk.IAP.Samples.Runtime.Demo_Item.DeserializeDemo_Item(_ele);
            _dataList.Add(_v);
        }
    }

    public NovaFramework.Runtime.DataTableMode Mode => NovaFramework.Runtime.DataTableMode.List;

    public global::System.Collections.Generic.IReadOnlyList<Demo_Item> DataList => _dataList;

    public Demo_Item this[int index] => _dataList[index];

    public void ResolveRef(TableTables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}
}

