// <nova-generated profile="vibrate-emphasis" source="Assets/Samples/FacebookDemo/Excels/Vibrates/Emphasis" artifact="TbDemo_VibrateEmphasis.cs" content-hash="sha256:7e0e6fa026be16b0b24009de2e4ecbdb7ac3011d64fd94a71b0076a3e615c438" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace NovaFramework.Sdk.Facebook.Samples.Runtime
{

/// <summary>
/// Demo_VibrateEmphasis
/// </summary>
public partial class TbDemo_VibrateEmphasis :
    NovaFramework.Runtime.ITable<Demo_VibrateEmphasis>
{
    private readonly global::System.Collections.Generic.List<Demo_VibrateEmphasis> _dataList;



    public TbDemo_VibrateEmphasis(JArray _buf)
    {
        _dataList = new global::System.Collections.Generic.List<Demo_VibrateEmphasis>(_buf.Count);

        foreach(JObject _ele in _buf)
        {
            Demo_VibrateEmphasis _v;
            _v = global::NovaFramework.Sdk.Facebook.Samples.Runtime.Demo_VibrateEmphasis.DeserializeDemo_VibrateEmphasis(_ele);
            _dataList.Add(_v);
        }
    }

    public NovaFramework.Runtime.DataTableMode Mode => NovaFramework.Runtime.DataTableMode.List;

    public global::System.Collections.Generic.IReadOnlyList<Demo_VibrateEmphasis> DataList => _dataList;

    public Demo_VibrateEmphasis this[int index] => _dataList[index];


    public void ResolveRef(VibrateEmphasisTables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}
}

