//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace NovaFramework.Kit.Network.GameSave.Samples.Runtime
{
public partial class LocalizationFontTables : NovaFramework.Runtime.ILubanTables
{
    /// <summary>
    /// LocalizationFonts
    /// </summary>
    public TbLocalizationFonts TbLocalizationFonts {get; }

    public LocalizationFontTables(global::System.Func<string, JArray> loader)
    {
        TbLocalizationFonts = new TbLocalizationFonts(loader("tblocalizationfonts"));
    }

    public void ResolveRef()
    {
        TbLocalizationFonts.ResolveRef(this);
    }

    public global::System.Collections.Generic.IReadOnlyList<NovaFramework.Runtime.ITable> GetAllTables()
    {
        return new NovaFramework.Runtime.ITable[]
        {
            TbLocalizationFonts,
        };
    }

    /// <summary>
    /// 获取指定类型的 Luban 表实例。
    /// </summary>
    /// <typeparam name="T">Luban 表类型。</typeparam>
    /// <returns>表实例，不存在时返回 null。</returns>
    public T GetTable<T>() where T : class, NovaFramework.Runtime.ITable
    {
        return GetTable(typeof(T)) as T;
    }

    /// <summary>
    /// 根据类型获取 Luban 表实例。
    /// </summary>
    /// <param name="type">表类型。</param>
    /// <returns>表实例，不存在时返回 null。</returns>
    public NovaFramework.Runtime.ITable GetTable(global::System.Type type)
    {
        global::System.Collections.Generic.IReadOnlyList<NovaFramework.Runtime.ITable> allTables = GetAllTables();
        for (int i = 0; i < allTables.Count; i++)
        {
            if (allTables[i].GetType() == type)
            {
                return allTables[i];
            }
        }
        return null;
    }
}

}

