// <nova-generated profile="ui" source="Assets/Samples/FirebaseDemo/Excels/UIs" artifact="UI1.cs" content-hash="sha256:185de5de3587f7bf98967f1dae2da50bddffe32d435fe9e6719e197b7473f8a6" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;
using NovaFramework.Runtime;



namespace NovaFramework.Sdk.Firebase.Samples.Runtime
{

public sealed partial class UI1 : Luban.BeanBase, NovaFramework.Runtime.IUIViewRow
{
    public UI1(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Name = (string)_obj.GetValue("Name");
        Desc = (string)_obj.GetValue("Desc");
        AssetLocation = (string)_obj.GetValue("AssetLocation");
        UIGroupName = (string)_obj.GetValue("UIGroupName");
        PauseCoveredUIView = (bool)_obj.GetValue("PauseCoveredUIView");
        InObjectPools = (bool)_obj.GetValue("InObjectPools");
    }

    public static UI1 DeserializeUI1(JToken _buf)
    {
        return new UI1(_buf);
    }

    /// <summary>
    /// UI测试表1
    /// </summary>
    public string Name { get; }
    public string Desc { get; }
    public string AssetLocation { get; }
    public string UIGroupName { get; }
    public bool PauseCoveredUIView { get; }
    public bool InObjectPools { get; }


    public const int __ID__ = 83997;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(UITables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "AssetLocation:" + AssetLocation + ","
        + "UIGroupName:" + UIGroupName + ","
        + "PauseCoveredUIView:" + PauseCoveredUIView + ","
        + "InObjectPools:" + InObjectPools + ","
        + "}";
    }
}
}

