// <nova-generated profile="localization-supported-languages" source="Assets/Samples/MainDemo/Excels/Localizations/Texts" artifact="TbLocalizationSupportedLanguages.cs" content-hash="sha256:62e697e8c4bb7dea01ef4a68dcb699a731c0933d682110b4aa138ee0f486c3ef" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace NovaFramework.Samples.Runtime
{

/// <summary>
/// Localization supported languages
/// </summary>
public partial class TbLocalizationSupportedLanguages :
    NovaFramework.Runtime.ITable<LocalizationSupportedLanguage>
{
    private readonly global::System.Collections.Generic.List<LocalizationSupportedLanguage> _dataList;



    public TbLocalizationSupportedLanguages(JArray _buf)
    {
        _dataList = new global::System.Collections.Generic.List<LocalizationSupportedLanguage>(_buf.Count);

        foreach(JObject _ele in _buf)
        {
            LocalizationSupportedLanguage _v;
            _v = global::NovaFramework.Samples.Runtime.LocalizationSupportedLanguage.DeserializeLocalizationSupportedLanguage(_ele);
            _dataList.Add(_v);
        }
    }

    public NovaFramework.Runtime.DataTableMode Mode => NovaFramework.Runtime.DataTableMode.List;

    public global::System.Collections.Generic.IReadOnlyList<LocalizationSupportedLanguage> DataList => _dataList;

    public LocalizationSupportedLanguage this[int index] => _dataList[index];


    public void ResolveRef(LocalizationSupportedLanguagesTables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}
}

