
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace NovaFramework.Samples.Runtime
{
public partial class TableTables : NovaFramework.Runtime.ILubanTables
{
    /// <summary>
    /// Demo_Item
    /// </summary>
    public TbDemo_Item TbDemoItem {get; }
    /// <summary>
    /// ListA
    /// </summary>
    public TbListA TbListA {get; }
    /// <summary>
    /// ListB
    /// </summary>
    public TbListB TbListB {get; }
    /// <summary>
    /// Map1
    /// </summary>
    public TbMap1 TbMap1 {get; }

    /// <summary>
    /// 使用 Luban JSON 加载器构造完整 Tables 容器。
    /// </summary>
    /// <param name="loader">按 output_data_file 返回 JSON 数组的加载器。</param>
    public TableTables(global::System.Func<string, JArray> loader)
    {
        TbDemoItem = new TbDemo_Item(loader("tbdemo_item"));
        TbListA = new TbListA(loader("tblista"));
        TbListB = new TbListB(loader("tblistb"));
        TbMap1 = new TbMap1(loader("tbmap1"));
    }

    /// <summary>
    /// 解析全部表之间的 Luban 引用。
    /// </summary>
    public void ResolveRef()
    {
        TbDemoItem.ResolveRef(this);
        TbListA.ResolveRef(this);
        TbListB.ResolveRef(this);
        TbMap1.ResolveRef(this);
    }

    /// <summary>
    /// 获取当前容器中的全部 Table 实例。
    /// </summary>
    /// <returns>只读 Table 列表。</returns>
    public global::System.Collections.Generic.IReadOnlyList<NovaFramework.Runtime.ITable> GetAllTables()
    {
        return new NovaFramework.Runtime.ITable[]
        {
            TbDemoItem,
            TbListA,
            TbListB,
            TbMap1,
        };
    }

    /// <summary>
    /// 获取指定类型的 Table 实例。
    /// </summary>
    /// <typeparam name="T">Table 类型。</typeparam>
    /// <returns>Table 实例，不存在时返回 null。</returns>
    public T GetTable<T>() where T : class, NovaFramework.Runtime.ITable
    {
        return GetTable(typeof(T)) as T;
    }

    /// <summary>
    /// 根据运行时类型获取 Table 实例。
    /// </summary>
    /// <param name="type">Table 运行时类型。</param>
    /// <returns>Table 实例，不存在时返回 null。</returns>
    public NovaFramework.Runtime.ITable GetTable(global::System.Type type)
    {
        global::System.Collections.Generic.IReadOnlyList<NovaFramework.Runtime.ITable> allTables = GetAllTables();
        for (int i = 0; i < allTables.Count; i++)
        {
            if (allTables[i].GetType() == type)
            {
                return allTables[i];
            }
        }
        return null;
    }
}

/// <summary>
/// 向 Nova 提供 TableTables 的原始文件清单与 JSON/MsgPack 解码方式。
/// </summary>
[global::UnityEngine.Scripting.Preserve]
public sealed class TableTablesBinding : NovaFramework.Runtime.ILubanTableBinding
{
    /// <summary>
    /// 获取当前 Tables 构造需要的全部 output_data_file。
    /// </summary>
    public global::System.Collections.Generic.IReadOnlyList<string> DataFiles { get; } = new string[]
    {
        "tbdemo_item",
        "tblista",
        "tblistb",
        "tbmap1",
    };

    /// <summary>
    /// 使用原始 JSON 或 MsgPack 字节构造 TableTables。
    /// </summary>
    /// <param name="loader">按 output_data_file 返回原始字节的加载器。</param>
    /// <returns>构造完成的 Tables 容器。</returns>
    public NovaFramework.Runtime.ILubanTables Create(global::System.Func<string, byte[]> loader)
    {
        var store = new NovaFramework.Runtime.TableDataStore();
        for (int i = 0; i < DataFiles.Count; i++)
        {
            store.Add(DataFiles[i], loader(DataFiles[i]));
        }
        byte[] first = store.GetBytes(DataFiles[0]);
        bool json = IsJson(first);
        return new TableTables(json ? store.GetJson : store.GetMsgPackJson);
    }

    /// <summary>
    /// 判断原始数据首个非空白字节是否为 JSON 数组起始符。
    /// </summary>
    /// <param name="bytes">待判断的原始数据。</param>
    /// <returns>是否为 JSON 数组。</returns>
    private static bool IsJson(byte[] bytes)
    {
        for (int i = 0; i < bytes.Length; i++)
        {
            byte value = bytes[i];
            if (value == 0x20 || value == 0x09 || value == 0x0A || value == 0x0D)
            {
                continue;
            }
            return value == 0x5B;
        }
        return false;
    }
}

}
