//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;

namespace NovaFramework.Sdk.Appsflyer.Samples.Runtime
{
/// <summary>
/// LocalizationFonts
/// </summary>
public partial class TbLocalizationFonts :
    NovaFramework.Runtime.ITable<LocalizationFonts>
{
    private readonly global::System.Collections.Generic.List<LocalizationFonts> _dataList;

    public TbLocalizationFonts(JArray _buf)
    {
        _dataList = new global::System.Collections.Generic.List<LocalizationFonts>(_buf.Count);

        foreach(JObject _ele in _buf)
        {
            LocalizationFonts _v;
            _v = global::NovaFramework.Sdk.Appsflyer.Samples.Runtime.LocalizationFonts.DeserializeLocalizationFonts(_ele);
            _dataList.Add(_v);
        }
    }

    public NovaFramework.Runtime.DataTableMode Mode => NovaFramework.Runtime.DataTableMode.List;

    public global::System.Collections.Generic.IReadOnlyList<LocalizationFonts> DataList => _dataList;

    public LocalizationFonts this[int index] => _dataList[index];

    public void ResolveRef(LocalizationFontTables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}
}

