// <nova-generated profile="vibrate-emphasis" source="Assets/Samples/AIHelpDemo/Excels/Vibrates/Emphasis" artifact="VibrateEmphasisTables.cs" content-hash="sha256:76e78ec3a829a2ace145bea4f803245a762e5a17cbc1e6f03fcbd29d1a816e85" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace NovaFramework.Sdk.Aihelp.Samples.Runtime
{
public partial class VibrateEmphasisTables : NovaFramework.Runtime.ILubanTables
{
    /// <summary>
    /// Demo_VibrateEmphasis
    /// </summary>
    public TbDemo_VibrateEmphasis TbDemoVibrateEmphasis {get; }

    public VibrateEmphasisTables(global::System.Func<string, JArray> loader)
    {
        TbDemoVibrateEmphasis = new TbDemo_VibrateEmphasis(loader("tbdemo_vibrateemphasis"));
    }

    public void ResolveRef()
    {
        TbDemoVibrateEmphasis.ResolveRef(this);
    }

    public global::System.Collections.Generic.IReadOnlyList<NovaFramework.Runtime.ITable> GetAllTables()
    {
        return new NovaFramework.Runtime.ITable[]
        {
            TbDemoVibrateEmphasis,
        };
    }

    /// <summary>
    /// 获取指定类型的 Luban 表实例。
    /// </summary>
    /// <typeparam name="T">Luban 表类型。</typeparam>
    /// <returns>表实例，不存在时返回 null。</returns>
    public T GetTable<T>() where T : class, NovaFramework.Runtime.ITable
    {
        return GetTable(typeof(T)) as T;
    }

    /// <summary>
    /// 根据类型获取 Luban 表实例。
    /// </summary>
    /// <param name="type">表类型。</param>
    /// <returns>表实例，不存在时返回 null。</returns>
    public NovaFramework.Runtime.ITable GetTable(global::System.Type type)
    {
        global::System.Collections.Generic.IReadOnlyList<NovaFramework.Runtime.ITable> allTables = GetAllTables();
        for (int i = 0; i < allTables.Count; i++)
        {
            if (allTables[i].GetType() == type)
            {
                return allTables[i];
            }
        }
        return null;
    }
}

}

