//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;
using NovaFramework.Runtime;

namespace NovaFramework.Sdk.Appsflyer.Samples.Runtime
{

public sealed partial class Demo_VibrateCustom : Luban.BeanBase, NovaFramework.Runtime.IVibrateCustomRow
{
    public Demo_VibrateCustom(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Name = (string)_obj.GetValue("Name");
        Intensity = (float)_obj.GetValue("Intensity");
        Sharpness = (float)_obj.GetValue("Sharpness");
        PreDuration = (float)_obj.GetValue("PreDuration");
        Duration = (float)_obj.GetValue("Duration");
        Order = (int)_obj.GetValue("Order");
    }

    public static Demo_VibrateCustom DeserializeDemo_VibrateCustom(JToken _buf)
    {
        return new Demo_VibrateCustom(_buf);
    }

    /// <summary>
    /// Demo 振动自定义组合表
    /// </summary>
    public string Name { get; }
    /// <summary>
    /// 振动强度
    /// </summary>
    public float Intensity { get; }
    /// <summary>
    /// 振动锐度
    /// </summary>
    public float Sharpness { get; }
    /// <summary>
    /// 前置等待时长
    /// </summary>
    public float PreDuration { get; }
    /// <summary>
    /// 振动持续时长
    /// </summary>
    public float Duration { get; }
    /// <summary>
    /// 播放顺序
    /// </summary>
    public int Order { get; }

    public const int __ID__ = -2076569500;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(VibrateCustomTables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "Intensity:" + Intensity + ","
        + "Sharpness:" + Sharpness + ","
        + "PreDuration:" + PreDuration + ","
        + "Duration:" + Duration + ","
        + "Order:" + Order + ","
        + "}";
    }
}
}

