// <nova-generated profile="network-hostkey" source="Assets/Samples/AdDemo/Excels/Networks/HostKeys" artifact="NetworkHostKeys.cs" content-hash="sha256:805df34092919d73f629c1d53e9ded186e8f18e92f0f426305f1a54d99ca4f6e" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;
using NovaFramework.Runtime;



namespace NovaFramework.Sdk.Ad.Samples.Runtime
{

public sealed partial class NetworkHostKeys : Luban.BeanBase, NovaFramework.Runtime.INetworkHostKeyRow
{
    public NetworkHostKeys(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Name = (string)_obj.GetValue("Name");
        Value = (string)_obj.GetValue("Value");
    }

    public static NetworkHostKeys DeserializeNetworkHostKeys(JToken _buf)
    {
        return new NetworkHostKeys(_buf);
    }

    /// <summary>
    /// 网络域名表（NetHosts）
    /// </summary>
    public string Name { get; }
    public string Value { get; }


    public const int __ID__ = 1722936298;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(HostKeyTables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

