// <nova-generated profile="network-hostkey" source="Assets/Samples/IAPDemo/Excels/Networks/HostKeys" artifact="NetworkHostKeys.cs" content-hash="sha256:591f5c1aa41d75e288dde2dd2d49d524b71c38006d760c9bf1b2af21b06ae76f" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;
using NovaFramework.Runtime;



namespace NovaFramework.Sdk.IAP.Samples.Runtime
{
/// <summary>
/// NetworkHostKeys
/// </summary>

public sealed partial class NetworkHostKeys : Luban.BeanBase, NovaFramework.Runtime.INetworkHostKeyRow
{
    public NetworkHostKeys(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Name = (string)_obj.GetValue("Name");
        Value = (string)_obj.GetValue("Value");
        FallbackValue = (string)_obj.GetValue("FallbackValue");
    }

    public static NetworkHostKeys DeserializeNetworkHostKeys(JToken _buf)
    {
        return new NetworkHostKeys(_buf);
    }

    /// <summary>
    /// 网络域名表（NetHosts）
    /// </summary>
    public string Name { get; }
    public string Value { get; }
    public string FallbackValue { get; }


    public const int __ID__ = 1722936298;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(HostKeyTables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "Value:" + Value + ","
        + "FallbackValue:" + FallbackValue + ","
        + "}";
    }
}
}

