//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;

namespace NovaFramework.Sdk.Ad.Samples.Runtime
{
/// <summary>
/// UI1
/// </summary>
public partial class TbUI1 :
    NovaFramework.Runtime.ITableMap<string, UI1>
{
    private readonly global::System.Collections.Generic.Dictionary<string, UI1> _dataMap;
    private readonly global::System.Collections.Generic.List<UI1> _dataList;

    public TbUI1(JArray _buf)
    {
        _dataMap = new global::System.Collections.Generic.Dictionary<string, UI1>(_buf.Count);
        _dataList = new global::System.Collections.Generic.List<UI1>(_buf.Count);

        foreach(JObject _ele in _buf)
        {
            UI1 _v;
            _v = global::NovaFramework.Sdk.Ad.Samples.Runtime.UI1.DeserializeUI1(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
         }
    }

    public NovaFramework.Runtime.DataTableMode Mode => NovaFramework.Runtime.DataTableMode.Map;

    public global::System.Collections.Generic.IReadOnlyDictionary<string, UI1> DataMap => _dataMap;
    public global::System.Collections.Generic.IReadOnlyList<UI1> DataList => _dataList;

    UI1 NovaFramework.Runtime.ITable<UI1>.this[int index] => _dataList[index];

    public UI1 GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public UI1 Get(string key) => _dataMap[key];
    public UI1 this[string key] => _dataMap[key];

    public void ResolveRef(UITables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}
#pragma warning disable

namespace NovaFramework.Sdk.Ad.Samples.Runtime
{
public partial class TbUI1
{
    /// <summary>
    /// 演示导航树视图
    /// </summary>
    public UI1 DemoNavTreeView => GetOrDefault("DemoNavTreeView");

    /// <summary>
    /// Core 1.1 FrameworkComponent
    /// </summary>
    public UI1 DemoFrameworkComponentView => GetOrDefault("DemoFrameworkComponentView");

    /// <summary>
    /// Core 1.2 FrameworkManager
    /// </summary>
    public UI1 DemoFrameworkManagerView => GetOrDefault("DemoFrameworkManagerView");

    /// <summary>
    /// Core 1.3 Fsm
    /// </summary>
    public UI1 DemoFsmView => GetOrDefault("DemoFsmView");

    /// <summary>
    /// Core 1.4 Reference
    /// </summary>
    public UI1 DemoReferenceView => GetOrDefault("DemoReferenceView");

    /// <summary>
    /// Core 1.5 Log
    /// </summary>
    public UI1 DemoLogView => GetOrDefault("DemoLogView");

    /// <summary>
    /// Core 1.6 Util
    /// </summary>
    public UI1 DemoUtilView => GetOrDefault("DemoUtilView");

    /// <summary>
    /// Core 1.7 Collections
    /// </summary>
    public UI1 DemoCollectionsView => GetOrDefault("DemoCollectionsView");

    /// <summary>
    /// Core 1.8 Extensions
    /// </summary>
    public UI1 DemoExtensionsView => GetOrDefault("DemoExtensionsView");

    /// <summary>
    /// Core 1.9 Edge Cases
    /// </summary>
    public UI1 DemoEdgeCasesView => GetOrDefault("DemoEdgeCasesView");

    /// <summary>
    /// Modules 2.1 App
    /// </summary>
    public UI1 DemoAppView => GetOrDefault("DemoAppView");

    /// <summary>
    /// Modules 2.2 Asset
    /// </summary>
    public UI1 DemoAssetView => GetOrDefault("DemoAssetView");

    /// <summary>
    /// Modules 2.3 Prefab
    /// </summary>
    public UI1 DemoPrefabView => GetOrDefault("DemoPrefabView");

    /// <summary>
    /// Modules 2.4 Config
    /// </summary>
    public UI1 DemoConfigView => GetOrDefault("DemoConfigView");

    /// <summary>
    /// Modules 2.5 Event
    /// </summary>
    public UI1 DemoEventView => GetOrDefault("DemoEventView");

    /// <summary>
    /// Modules 2.6 Table
    /// </summary>
    public UI1 DemoTableView => GetOrDefault("DemoTableView");

    /// <summary>
    /// Modules 2.7 Localization
    /// </summary>
    public UI1 DemoLocalizationView => GetOrDefault("DemoLocalizationView");

    /// <summary>
    /// Modules 2.8 UI
    /// </summary>
    public UI1 DemoUIView => GetOrDefault("DemoUIView");

    /// <summary>
    /// Modules 2.9 Network
    /// </summary>
    public UI1 DemoNetworkView => GetOrDefault("DemoNetworkView");

    /// <summary>
    /// Modules 2.10 Procedure
    /// </summary>
    public UI1 DemoProcedureView => GetOrDefault("DemoProcedureView");

    /// <summary>
    /// Modules 2.11 ObjectPool
    /// </summary>
    public UI1 DemoObjectPoolView => GetOrDefault("DemoObjectPoolView");

    /// <summary>
    /// Modules 2.12 Persist
    /// </summary>
    public UI1 DemoPersistView => GetOrDefault("DemoPersistView");

    /// <summary>
    /// Modules 2.13 Sound
    /// </summary>
    public UI1 DemoSoundView => GetOrDefault("DemoSoundView");

    /// <summary>
    /// Modules 2.14 Vibrate
    /// </summary>
    public UI1 DemoVibrateView => GetOrDefault("DemoVibrateView");

    /// <summary>
    /// Modules 2.15 SDK
    /// </summary>
    public UI1 DemoSDKView => GetOrDefault("DemoSDKView");

    /// <summary>
    /// Modules 2.16 Debug
    /// </summary>
    public UI1 DemoDebugView => GetOrDefault("DemoDebugView");

    /// <summary>
    /// HybridCLR 3.1 AOT metadata
    /// </summary>
    public UI1 DemoHybridClrAotMetadataView => GetOrDefault("DemoHybridClrAotMetadataView");

    /// <summary>
    /// HybridCLR 3.2 业务 dll
    /// </summary>
    public UI1 DemoHybridClrGameDllView => GetOrDefault("DemoHybridClrGameDllView");

    /// <summary>
    /// HybridCLR 3.3 Procedure 注册时序
    /// </summary>
    public UI1 DemoHybridClrProcedureRegisterView => GetOrDefault("DemoHybridClrProcedureRegisterView");

    /// <summary>
    /// Integration 4.1 UI+Localization
    /// </summary>
    public UI1 DemoIntegrationUiLocalizationView => GetOrDefault("DemoIntegrationUiLocalizationView");

    /// <summary>
    /// Integration 4.2 UI+Asset
    /// </summary>
    public UI1 DemoIntegrationUiAssetView => GetOrDefault("DemoIntegrationUiAssetView");

    /// <summary>
    /// Integration 4.3 Procedure+Asset
    /// </summary>
    public UI1 DemoIntegrationProcedureAssetView => GetOrDefault("DemoIntegrationProcedureAssetView");

    /// <summary>
    /// Integration 4.4 Event+Network
    /// </summary>
    public UI1 DemoIntegrationEventNetworkView => GetOrDefault("DemoIntegrationEventNetworkView");

    /// <summary>
    /// Integration 4.5 Config+HybridCLR
    /// </summary>
    public UI1 DemoIntegrationConfigHybridClrView => GetOrDefault("DemoIntegrationConfigHybridClrView");

    /// <summary>
    /// Demo 辅助 Toast 弹窗
    /// </summary>
    public UI1 DemoToastView => GetOrDefault("DemoToastView");

    /// <summary>
    /// Demo 辅助 Dialog 弹窗
    /// </summary>
    public UI1 DemoDialogView => GetOrDefault("DemoDialogView");

}
}
#pragma warning restore
