// <nova-generated profile="localization-text" source="Assets/Samples/GoogleSigninDemo/Excels/Localizations/Texts" artifact="Demo_Localization.cs" content-hash="sha256:77db7811ab95c143a34ed2e4d7cfdbdc4fd9c3f7d5abc5ed1f4065fac47d8ee3" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;
using NovaFramework.Runtime;



namespace NovaFramework.Sdk.Googlesignin.Samples.Runtime
{

public sealed partial class Demo_Localization : Luban.BeanBase, NovaFramework.Runtime.ILocalizationTextRow
{
    public Demo_Localization(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Name = (string)_obj.GetValue("Name");
        Value = (string)_obj.GetValue("Value");
    }

    public static Demo_Localization DeserializeDemo_Localization(JToken _buf)
    {
        return new Demo_Localization(_buf);
    }

    /// <summary>
    /// Demo_Localization
    /// </summary>
    public string Name { get; }
    public string Value { get; }


    public const int __ID__ = -112808075;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(LocalizationTextTables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "Value:" + Value + ","
        + "}";
    }
}
}

