// <nova-generated profile="network-cmd" source="Assets/Samples/FirebaseDemo/Excels/Networks/Cmds" artifact="NetworkCmds.cs" content-hash="sha256:17bf6741ba6514f20f44a6293028c7cf6e92d0c40e68800823086b6c343f84d0" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;
using NovaFramework.Runtime;



namespace NovaFramework.Sdk.Firebase.Samples.Runtime
{

public sealed partial class NetworkCmds : Luban.BeanBase, NovaFramework.Runtime.INetworkCmdRow
{
    public NetworkCmds(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Name = (string)_obj.GetValue("Name");
        Way = (string)_obj.GetValue("Way");
        HostKey = (string)_obj.GetValue("HostKey");
        Path = (string)_obj.GetValue("Path");
    }

    public static NetworkCmds DeserializeNetworkCmds(JToken _buf)
    {
        return new NetworkCmds(_buf);
    }

    /// <summary>
    /// 网络指令表（NetCmds）
    /// </summary>
    public string Name { get; }
    public string Way { get; }
    public string HostKey { get; }
    public string Path { get; }


    public const int __ID__ = -273263193;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(NetworkTables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Name:" + Name + ","
        + "Way:" + Way + ","
        + "HostKey:" + HostKey + ","
        + "Path:" + Path + ","
        + "}";
    }
}
}

