// <nova-generated profile="vibrate-custom" source="Assets/Samples/MainDemo/Excels/Vibrates/Customs" artifact="TbDemo_VibrateCustom.cs" content-hash="sha256:e59f6926ef928a29f320c37ba821fba78ce961a649da2d1f3d2debc414c67b4c" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace NovaFramework.Samples.Runtime
{

/// <summary>
/// Demo_VibrateCustom
/// </summary>
public partial class TbDemo_VibrateCustom :
    NovaFramework.Runtime.ITable<Demo_VibrateCustom>
{
    private readonly global::System.Collections.Generic.List<Demo_VibrateCustom> _dataList;



    public TbDemo_VibrateCustom(JArray _buf)
    {
        _dataList = new global::System.Collections.Generic.List<Demo_VibrateCustom>(_buf.Count);

        foreach(JObject _ele in _buf)
        {
            Demo_VibrateCustom _v;
            _v = global::NovaFramework.Samples.Runtime.Demo_VibrateCustom.DeserializeDemo_VibrateCustom(_ele);
            _dataList.Add(_v);
        }
    }

    public NovaFramework.Runtime.DataTableMode Mode => NovaFramework.Runtime.DataTableMode.List;

    public global::System.Collections.Generic.IReadOnlyList<Demo_VibrateCustom> DataList => _dataList;

    public Demo_VibrateCustom this[int index] => _dataList[index];


    public void ResolveRef(VibrateCustomTables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}
}

