//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;

namespace NovaFramework.Sdk.Tga.Samples.Runtime
{
/// <summary>
/// NetworkCmds
/// </summary>
public partial class TbNetworkCmds :
    NovaFramework.Runtime.ITableMap<string, NetworkCmds>
{
    private readonly global::System.Collections.Generic.Dictionary<string, NetworkCmds> _dataMap;
    private readonly global::System.Collections.Generic.List<NetworkCmds> _dataList;

    public TbNetworkCmds(JArray _buf)
    {
        _dataMap = new global::System.Collections.Generic.Dictionary<string, NetworkCmds>(_buf.Count);
        _dataList = new global::System.Collections.Generic.List<NetworkCmds>(_buf.Count);

        foreach(JObject _ele in _buf)
        {
            NetworkCmds _v;
            _v = global::NovaFramework.Sdk.Tga.Samples.Runtime.NetworkCmds.DeserializeNetworkCmds(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
         }
    }

    public NovaFramework.Runtime.DataTableMode Mode => NovaFramework.Runtime.DataTableMode.Map;

    public global::System.Collections.Generic.IReadOnlyDictionary<string, NetworkCmds> DataMap => _dataMap;
    public global::System.Collections.Generic.IReadOnlyList<NetworkCmds> DataList => _dataList;

    NetworkCmds NovaFramework.Runtime.ITable<NetworkCmds>.this[int index] => _dataList[index];

    public NetworkCmds GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public NetworkCmds Get(string key) => _dataMap[key];
    public NetworkCmds this[string key] => _dataMap[key];

    public void ResolveRef(NetworkTables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}
#pragma warning disable

namespace NovaFramework.Sdk.Tga.Samples.Runtime
{
public partial class TbNetworkCmds
{
    public NetworkCmds GameAccountLogin => GetOrDefault("GameAccountLogin");

    public NetworkCmds TGAReport => GetOrDefault("TGAReport");

    public NetworkCmds TGAServerUrl => GetOrDefault("TGAServerUrl");

}
}
#pragma warning restore
