//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;

namespace NovaFramework.Kit.Network.GameSave.Samples.Runtime
{

public sealed partial class Demo_Item : Luban.BeanBase
{
    public Demo_Item(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("Id");
        Name = (string)_obj.GetValue("Name");
        Icon = (string)_obj.GetValue("Icon");
        Price = (int)_obj.GetValue("Price");
    }

    public static Demo_Item DeserializeDemo_Item(JToken _buf)
    {
        return new Demo_Item(_buf);
    }

    /// <summary>
    /// Demo 演示物品表
    /// </summary>
    public int Id { get; }
    public string Name { get; }
    public string Icon { get; }
    public int Price { get; }

    public const int __ID__ = -1496121361;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(TableTables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Icon:" + Icon + ","
        + "Price:" + Price + ","
        + "}";
    }
}
}

