//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;

namespace NovaFramework.Kit.Network.GameSave.Samples.Runtime
{
/// <summary>
/// Map1
/// </summary>
public partial class TbMap1 :
    NovaFramework.Runtime.ITableMap<string, Map1>
{
    private readonly global::System.Collections.Generic.Dictionary<string, Map1> _dataMap;
    private readonly global::System.Collections.Generic.List<Map1> _dataList;

    public TbMap1(JArray _buf)
    {
        _dataMap = new global::System.Collections.Generic.Dictionary<string, Map1>(_buf.Count);
        _dataList = new global::System.Collections.Generic.List<Map1>(_buf.Count);

        foreach(JObject _ele in _buf)
        {
            Map1 _v;
            _v = global::NovaFramework.Kit.Network.GameSave.Samples.Runtime.Map1.DeserializeMap1(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
         }
    }

    public NovaFramework.Runtime.DataTableMode Mode => NovaFramework.Runtime.DataTableMode.Map;

    public global::System.Collections.Generic.IReadOnlyDictionary<string, Map1> DataMap => _dataMap;
    public global::System.Collections.Generic.IReadOnlyList<Map1> DataList => _dataList;

    Map1 NovaFramework.Runtime.ITable<Map1>.this[int index] => _dataList[index];

    public Map1 GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Map1 Get(string key) => _dataMap[key];
    public Map1 this[string key] => _dataMap[key];

    public void ResolveRef(TableTables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}
#pragma warning disable

namespace NovaFramework.Kit.Network.GameSave.Samples.Runtime
{
public partial class TbMap1
{
    /// <summary>
    /// XXXXX
    /// </summary>
    public Map1 XXXXX => GetOrDefault("XXXXX");

}
}
#pragma warning restore
