// <nova-generated profile="ui" source="Assets/Samples/IAPDemo/Excels/UIs" artifact="TbUI1.cs" content-hash="sha256:d35b8539562ad79937fa51d6c660bc4f8150325a9bc88a7bdd5b7fa1a72acf0e" />

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace NovaFramework.Sdk.IAP.Samples.Runtime
{

/// <summary>
/// UI1
/// </summary>
public partial class TbUI1 :
    NovaFramework.Runtime.ITableMap<string, UI1>
{
    private readonly global::System.Collections.Generic.Dictionary<string, UI1> _dataMap;
    private readonly global::System.Collections.Generic.List<UI1> _dataList;

    public TbUI1(JArray _buf)
    {
        _dataMap = new global::System.Collections.Generic.Dictionary<string, UI1>(_buf.Count);
        _dataList = new global::System.Collections.Generic.List<UI1>(_buf.Count);

        foreach(JObject _ele in _buf)
        {
            UI1 _v;
            _v = global::NovaFramework.Sdk.IAP.Samples.Runtime.UI1.DeserializeUI1(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Name, _v);
         }
    }

    public NovaFramework.Runtime.DataTableMode Mode => NovaFramework.Runtime.DataTableMode.Map;

    public global::System.Collections.Generic.IReadOnlyDictionary<string, UI1> DataMap => _dataMap;
    public global::System.Collections.Generic.IReadOnlyList<UI1> DataList => _dataList;

    UI1 NovaFramework.Runtime.ITable<UI1>.this[int index] => _dataList[index];

    public UI1 GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public UI1 Get(string key) => _dataMap[key];
    public UI1 this[string key] => _dataMap[key];

    public void ResolveRef(UITables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

// --- AUTO-GENERATED MAP PROPERTIES BEGIN ---
#pragma warning disable

namespace NovaFramework.Sdk.IAP.Samples.Runtime
{
public partial class TbUI1
{
    /// <summary>
    /// IAP 演示 Demo 视图
    /// </summary>
    public UI1 DemoIAPView => GetOrDefault("DemoIAPView");

}
}
#pragma warning restore

// --- AUTO-GENERATED MAP PROPERTIES END ---
